spring:
  profiles:
    active:
    -dev
---
 spring:
   profiles: dev 
   application: 
      name:   spring-config-api-dev  
---
 spring:
   profiles: test 
   application: 
      name:   spring-config-api-test  
      
      
      
      
      
      